[build]
  command = "npm run build:no-prerender"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"

[[redirects]]
  from = "/zero.txt"
  to = "/zero.txt"
  status = 200

[[redirects]]
  from = "/zeroth.txt"
  to = "/zeroth.txt"
  status = 200

[[redirects]]
  from = "/:1/*"
  to = "/:1/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

