[build]
  command = "yarn build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"

[dev]
  targetPort = 8081

[[redirects]]
  from = "/zero.txt"
  to = "/zero.txt"
  status = 200

[[redirects]]
  from = "/zeroth.txt"
  to = "/zeroth.txt"
  status = 200

[[redirects]]
  from = "/audio/*"
  to = "/audio/:splat"
  status = 200

[[redirects]]
  from = "/*.txt"
  to = "/:splat.txt"
  status = 200

[[redirects]]
  from = "/*melinda*"
  to = "/melinda"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

