/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/Dr.MelindaFrancis.com`; params?: Router.UnknownInputParams; } | { pathname: `/cryptofabric`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/thd`; params?: Router.UnknownInputParams; } | { pathname: `/thth`; params?: Router.UnknownInputParams; } | { pathname: `/zero`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/blog`; params?: Router.UnknownInputParams; } | { pathname: `/interview/1`; params?: Router.UnknownInputParams; } | { pathname: `/interview/2`; params?: Router.UnknownInputParams; } | { pathname: `/interview/3`; params?: Router.UnknownInputParams; } | { pathname: `/interview`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/blog/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/Dr.MelindaFrancis.com`; params?: Router.UnknownOutputParams; } | { pathname: `/cryptofabric`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/thd`; params?: Router.UnknownOutputParams; } | { pathname: `/thth`; params?: Router.UnknownOutputParams; } | { pathname: `/zero`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/blog`; params?: Router.UnknownOutputParams; } | { pathname: `/interview/1`; params?: Router.UnknownOutputParams; } | { pathname: `/interview/2`; params?: Router.UnknownOutputParams; } | { pathname: `/interview/3`; params?: Router.UnknownOutputParams; } | { pathname: `/interview`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } } | { pathname: `/blog/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/Dr.MelindaFrancis.com${`?${string}` | `#${string}` | ''}` | `/cryptofabric${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/thd${`?${string}` | `#${string}` | ''}` | `/thth${`?${string}` | `#${string}` | ''}` | `/zero${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/blog${`?${string}` | `#${string}` | ''}` | `/interview/1${`?${string}` | `#${string}` | ''}` | `/interview/2${`?${string}` | `#${string}` | ''}` | `/interview/3${`?${string}` | `#${string}` | ''}` | `/interview${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/Dr.MelindaFrancis.com`; params?: Router.UnknownInputParams; } | { pathname: `/cryptofabric`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/thd`; params?: Router.UnknownInputParams; } | { pathname: `/thth`; params?: Router.UnknownInputParams; } | { pathname: `/zero`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/blog`; params?: Router.UnknownInputParams; } | { pathname: `/interview/1`; params?: Router.UnknownInputParams; } | { pathname: `/interview/2`; params?: Router.UnknownInputParams; } | { pathname: `/interview/3`; params?: Router.UnknownInputParams; } | { pathname: `/interview`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | `/blog/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/blog/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
